name: Tests execution

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B test --file pom.xml

      - name: Test Reporter
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: Tests
          path: '**/target/surefire-reports/TEST-*.xml'
          reporter: java-junit

